version: 0.2

phases:
  install:
    commands:
      - echo "Updating package list..."
      - apt update -y
      - echo "Installing dependencies..."
      - apt install -y unzip nginx default-jdk
      - echo "Dependencies installed successfully"
  pre_build:
    commands:
      - echo "Preparing build environment..."
      - mkdir -p /tmp/unzipped
      - echo "Build environment ready"
  build:
    commands:
      - echo "Build started on `date`"
      - echo "Searching for zip file"
      - ZIP_FILE=$(find . -name "*.zip" | head -n 1)
      - echo "Zip file found: $ZIP_FILE"
      - if [ -z "$ZIP_FILE" ]; then echo "No zip file found. Exiting." && exit 1; fi
      - echo "Verifying if zip file exists and is not empty"
      - if [ ! -f "$ZIP_FILE" ] || [ ! -s "$ZIP_FILE" ]; then echo "Zip file does not exist or is empty. Exiting." && exit 1; fi
      - echo "Zip file is present and has content"
      - echo "Checking zip file integrity"
      - unzip -t "$ZIP_FILE" || (echo "Zip file integrity check failed. Exiting." && exit 1)
      - echo "Unzipping source code using default method"
      - unzip -o "$ZIP_FILE" -d /tmp/unzipped || echo "Default unzip failed. Trying alternative method"
      - echo "Trying alternative method to unzip"
      - jar xf "$ZIP_FILE" -C /tmp/unzipped
      - echo "Listing files in /tmp/unzipped"
      - ls -l /tmp/unzipped
      - echo "Copying files to Nginx web root"
      - cp -r /tmp/unzipped/* /var/www/html/
      - echo "Files copied successfully"
  post_build:
    commands:
      - echo "Restarting Nginx"
      - systemctl restart nginx
      - echo "Nginx restarted successfully"
      - echo "Build completed on `date`"
artifacts:
  files:
    - '**/*'
  discard-paths: yes
cache:
  paths:
    - '/tmp/unzipped/**/*'
