version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
      - apt update -y
      - apt install -y unzip curl
  build:
    commands:
      - echo Build started on `date`
      - echo Listing files in current directory
      - ls -l
      - echo Searching for zip file
      - find . -name "*.zip"
      - echo Creating temp directory
      - mkdir -p /tmp/unzipped
      - echo Unzipping source code
      - unzip -o $(find . -name "*.zip" | head -n 1) -d /tmp/unzipped
      - echo Listing files in /tmp/unzipped
      - ls -l /tmp/unzipped
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
