version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9  # Change version if needed
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt  # Install dependencies

  pre_build:
    commands:
      - echo "Running pre-build tests..."
      - python -m unittest discover -s tests  # Run unit tests (optional)

  build:
    commands:
      - echo "Starting build..."
      - python my_script.py  # Change to your main script

  post_build:
    commands:
      - echo "Build completed successfully!"

artifacts:
  files:
    - '**/*'  # Store all files as artifacts

