version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Packaging Lambda function...
      - zip -r function.zip index.js
      - aws lambda update-function-code --function-name LambdaEC2Deployment --zip-file fileb://function.zip
artifacts:
  files:
    - function.zip
