version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
      - yum update -y
      - yum install -y unzip curl
  build:
    commands:
      - echo Build started on `date`
      - echo Unzipping source code
      - unzip source-code.zip -d /var/www/html
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'

